export enum TripStatus {
  INQUIRY = 'INQUIRY',
  RESEARCH = 'RESEARCH',
  QUOTED = 'QUOTED',
  REVISED = 'REVISED',
  APPROVED = 'APPROVED',
  CONFIRMED = 'CONFIRMED',
  FINALIZED = 'FINALIZED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
